ghc:
- 7.8
- 7.6
install:
- git fetch --unshallow
- cabal install 'hi ==0.0.8.*'
- cd package-name/tmp
- hi
    --author 'Travis CI'
    --email 'travis-ci@example.com'
    --module-name Travis.CI
    --repository "file://$(dirname $(dirname $(pwd)))"
- cd travis-ci
- make install
language: haskell
script:
- make configure build test bench
- runhaskell haskeleton.hs An.Example
- make configure build test bench
